// Generated by scripts/build.mjs — edit original module sources, then rebuild.
export async function mount(ctx) {
const {document,window,navigator,location,history,fetch,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame,cancelAnimationFrame}=ctx;

{
window.SAHMT_TRAINING_CONFIG = Object.freeze({
  // Deploy NativeApi.gs alongside Code.gs at this existing endpoint before release.
  apiUrl: 'https://script.google.com/macros/s/AKfycbw8tyhilyC8czRrho0iOugr7B6L5COFZjm2x5Di4HuzsgTsw3SSlbVDFLexzYmN0m1j0g/exec'
});

}
{
(async () => {
  const $=id=>document.getElementById(id);
  let catalog=[],selected=null,accessId='',player=null,timer=null,last=0,ended=false,asked=false,busy=false,openGeneration=0;
  let watched=new Set();
  const email=()=>window.SAHMT_AUTH.getSession()?.email||'';
  const progressKey=id=>'sahmt-training-progress-v1:'+email()+':'+id;
  function saved(id){try{return JSON.parse(localStorage.getItem(progressKey(id))||'null');}catch{return null;}}
  function persist(){if(!selected||!player)return;try{localStorage.setItem(progressKey(selected.id),JSON.stringify({position:player.getCurrentTime?.()||0,watched:[...watched],asked,ended}));}catch{}}
  async function api(action,payload={}){
    await window.SAHMT_AUTH.requireAccess({moduleId:'TREINAMENTOS',pageId:action});
    const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);
    try{
      const response=await fetch(window.SAHMT_TRAINING_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},cache:'no-store',body:JSON.stringify(window.SAHMT_AUTH.withPayload({action,...payload})),signal:controller.signal});
      let value;try{value=JSON.parse(await response.text());}catch{throw new Error('Não foi possível carregar os treinamentos. Tente novamente em instantes.');}
      if(!response.ok||value.ok!==true)throw new Error(value.message||'Não foi possível concluir a operação.');
      if(value.apiVersion!==1)throw new Error('O serviço de treinamentos está indisponível no momento.');
      return value;
    }catch(e){if(e.name==='AbortError')throw new Error('A consulta demorou. Tente novamente.');throw e;}finally{clearTimeout(timeout);}
  }
  function status(text){$('training-status').textContent=text;}
  async function load(){
    $('training-retry').hidden=true;status('Carregando treinamentos…');
    try{const data=await api('catalog');if(!Array.isArray(data.trainings))throw new Error('Não foi possível ler o catálogo.');catalog=data.trainings;render(data);status(catalog.length?'':'Nenhum treinamento disponível.');}
    catch(e){status(e.message);$('training-retry').hidden=false;}
  }
  function render(data){
    $('training-score').replaceChildren(document.createTextNode(`Sua pontuação: ${data.totalPoints} / ${data.totalAvailablePoints} pontos · `));const percent=document.createElement('strong');percent.textContent=`${data.scorePercentage}%`;$('training-score').append(percent);
    $('training-catalog').replaceChildren();for(const item of catalog){const button=document.createElement('button');button.className='training-item'+(item.completed?' completed':'');const label=document.createElement('span'),title=document.createElement('strong');title.textContent=item.title;label.append(title);if(saved(item.id)&&!item.completed){const resume=document.createElement('small');resume.textContent='Continuar de onde parou';label.append(resume);}const points=document.createElement('span');points.className='points';points.textContent=`${item.completed?'✓ ':''}${item.accessPoints+item.completionPoints} Pontos`;button.append(label,points);button.onclick=()=>open(item).catch(e=>{$('player-status').textContent=e.message;status(e.message);});$('training-catalog').append(button);}
  }
  async function youtube(){return window.SAHMT_SHELL.youtube();}
  async function open(item){
    if(busy)return;busy=true;const generation=++openGeneration;
    try{const started=await api('begin',{trainingId:item.id});if(generation!==openGeneration||document.hidden)return;selected=item;accessId=started.accessId;const old=saved(item.id);watched=new Set(old?.watched||[]);asked=!!old?.asked;ended=!!old?.ended;
      $('training-title').textContent=item.title;$('player-status').textContent='Carregando vídeo…';$('training-complete').disabled=true;$('training-play').disabled=true;$('training-player').showModal();
      const YT=await youtube();if(generation!==openGeneration||document.hidden)return;player?.destroy();$('training-video-wrap').replaceChildren();const el=document.createElement('div');el.id='training-video';$('training-video-wrap').append(el);
      player=new YT.Player(el,{videoId:item.videoId,playerVars:{playsinline:1,autoplay:0,loop:0,controls:0,disablekb:1,cc_load_policy:0,rel:0,origin:window.location.origin},events:{onReady:()=>{if(generation!==openGeneration||!player)return;if(old?.position&&!old.ended)player.seekTo(old.position,true);last=player.getCurrentTime()||0;$('training-play').disabled=false;$('player-status').textContent=old?'Continue de onde parou.':'Assista ao vídeo para concluir.';update();},onStateChange:e=>{if(generation!==openGeneration||!player)return;clearInterval(timer);if(e.data===YT.PlayerState.PLAYING){last=player.getCurrentTime();timer=setInterval(tick,1000);$('training-play').textContent='PAUSAR';}else $('training-play').textContent='REPRODUZIR';if(e.data===YT.PlayerState.ENDED){tick();ended=true;persist();update();}},onError:()=>{$('player-status').textContent='Não foi possível reproduzir este vídeo.';}}});
    }finally{if(generation===openGeneration)busy=false;}
  }
  function tick(){if(!player||!selected)return;const pos=player.getCurrentTime(),delta=pos-last,duration=player.getDuration();if(delta>0&&delta<=2.5)for(let s=Math.floor(last);s<Math.floor(pos);s++)watched.add(s);last=pos;if(!asked&&duration>0&&pos>=duration/2){asked=true;player.pauseVideo();$('training-question').showModal();}persist();update();}
  function update(){const duration=player?.getDuration?.()||0,ratio=duration?Math.min(1,watched.size/duration):0;$('training-progress').value=Math.round(ratio*100);$('training-complete').disabled=!(ended&&ratio>=.95);}
  function pause(){player?.pauseVideo?.();persist();clearInterval(timer);}
  function leavePlayer(){openGeneration++;pause();player?.destroy();player=null;selected=null;busy=false;if($('training-question').open)$('training-question').close();}
  async function back(){leavePlayer();$('training-player').close();await load();}
  $('training-play').onclick=()=>{if(!player)return;player.getPlayerState()===1?player.pauseVideo():player.playVideo();};
  for(const id of ['training-yes','training-no'])$(id).onclick=()=>{$('training-question').close();player?.playVideo();};
  $('training-complete').onclick=async()=>{if(busy||$('training-complete').disabled)return;busy=true;const completedKey=progressKey(selected.id),completionGeneration=openGeneration;$('training-complete').disabled=true;try{const result=await api('complete',{trainingId:selected.id,accessId,duration:player.getDuration(),watchedSeconds:watched.size,ended});localStorage.removeItem(completedKey);if(completionGeneration!==openGeneration)return;$('player-status').textContent=result.alreadyCompleted?'Treinamento já concluído.':'Conclusão registrada com sucesso.';}catch(e){if(completionGeneration===openGeneration){$('player-status').textContent=e.message;update();}}finally{if(completionGeneration===openGeneration)busy=false;}};
  $('training-back').onclick=back;$('training-player').addEventListener('cancel',e=>{e.preventDefault();back();});$('training-retry').onclick=load;
  document.addEventListener('sahmt:hide',leavePlayer);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
  document.addEventListener('sahmt:show',()=>{const id=new URL(window.location.href).searchParams.get('trainingId');if(id&&catalog.some(t=>t.id===id)&&selected?.id!==id)open(catalog.find(t=>t.id===id)).catch(e=>status(e.message));});
  await load();
  if(!document.hidden)document.dispatchEvent(new Event('sahmt:show'));
})();

}
}
