import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';
const dir='auth/apps-script/';const source=(await Promise.all(['Config.gs','LegacyEtiquetas.gs','CentralAuth.gs','Code.gs'].map(f=>fs.readFile(dir+f,'utf8')))).join('\n');
function setup(){const c={console,Date};vm.createContext(c);vm.runInContext(source,c);c.jsonResponse=x=>x;return c;}
const email='wx2064@gmail.com',token='a'.repeat(64);
test('all six modules validate through one auth route without app setup or history writes',()=>{const c=setup();c.requireAuthorized_=()=>({email,name:'Test',trustedDeviceExpiresAt:'2099-01-01T00:00:00Z'});c.ensureWorkbook_=()=>{throw Error('Must not initialize labels');};c.registerAccessHistory_=()=>{throw Error('Must not write history during auth');};for(const moduleId of ['HOME','EVENTOS','GESTAO','ETIQUETAS','CHECKLIST','TREINAMENTOS']){const r=c.doPost({postData:{contents:JSON.stringify({action:'auth',deviceToken:token,userEmail:email,moduleId})}});assert.equal(r.ok,true);assert.equal(r.email,email);}});
test('removed allowlist email cannot use a previously trusted device',()=>{const c=setup();c.findTrustedDeviceUser_=()=>{throw Error('Should be denied first');};assert.throws(()=>c.requireAuthorized_('',token,'removed@example.invalid'),e=>e.code==='FORBIDDEN');});
test('trusted device cannot impersonate a different email or use expired or revoked row',()=>{const c=setup();let row=[token,email,'Test',new Date(),new Date(),new Date('2099-01-01'),'ATIVO'];c.ensureTrustedDevicesSheet_=()=>({getDataRange:()=>({getValues:()=>[[],row]})});assert.equal(c.findTrustedDeviceUser_(token,'other@example.invalid'),null);assert.equal(c.findTrustedDeviceUser_(token,email).email,email);row[6]='REVOGADO';assert.throws(()=>c.findTrustedDeviceUser_(token,email),e=>e.code==='REVOKED');row[6]='ATIVO';row[5]=new Date('2000-01-01');assert.equal(c.findTrustedDeviceUser_(token,email),null);});
test('google token issuer, audience and expiry are verified',()=>{const c=setup();const valid={aud:vm.runInContext('GOOGLE_CLIENT_ID',c),iss:'https://accounts.google.com',exp:Math.floor(Date.now()/1000)+600,email,email_verified:'true'};let payload={...valid};c.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify(payload)})};assert.equal(c.verifyGoogleIdToken_('mock').email,email);for(const override of [{aud:'wrong'},{iss:'wrong'},{exp:1},{email_verified:'false'}]){payload={...valid,...override};assert.throws(()=>c.verifyGoogleIdToken_('mock'));}});
test('audit write failure does not turn authenticated user into denied session',()=>{const c=setup();c.console={error(){}};c.requireAuthorized_=()=>({email,name:'Test'});c.registerAccessHistory_=()=>{throw Error('quota');};const result=c.handleTrack_({moduleId:'GESTAO'});assert.equal(result.ok,true);assert.equal(result.historyRecorded,false);});
test('trusted last-access write is throttled for rapid module calls',()=>{const c=setup();let writes=0;let last=new Date();c.ensureTrustedDevicesSheet_=()=>({getDataRange:()=>({getValues:()=>[[],[token,email,'Test',new Date(),last,new Date('2099-01-01'),'ATIVO']]}),getRange:()=>({setValue:()=>writes++})});c.touchTrustedDevice_(token,email);assert.equal(writes,0);last=new Date(Date.now()-600000);c.touchTrustedDevice_(token,email);assert.equal(writes,1);});
test('legacy labels requests remain routed to their original handlers',()=>{const c=setup();c.legacyDoGet_=()=>({legacy:'get'});c.legacyDoPost_=()=>({legacy:'post'});assert.equal(c.doGet({parameter:{action:'summary'}}).legacy,'get');assert.equal(c.doPost({postData:{contents:'{"action":"aiExtract"}'}}).legacy,'post');});
test('new Google login cannot silently reactivate a revoked device',()=>{const c=setup();c.ensureTrustedDevicesSheet_=()=>({getDataRange:()=>({getValues:()=>[[],[token,email,'Test',new Date(),new Date(),new Date('2099-01-01'),'REVOGADO']]})});assert.throws(()=>c.registerTrustedDeviceUnlocked_(token,{email,name:'Test'}),e=>e.code==='REVOKED');});
