import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';
const code=await fs.readFile('apps/checklist/apps-script/Code.gs','utf8');
const owners=await fs.readFile('apps/checklist/apps-script/Responsaveis.gs','utf8');
function setup(enabled=false){const properties=new Map(enabled?[['CHECKLIST_SCHEDULED_SCORE','1']]:[]);const c={ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})},Utilities:{formatDate:()=> '2026-09-14',DigestAlgorithm:{SHA_256:'sha256'},computeDigest:()=>[1],base64EncodeWebSafe:()=> 'revision'},SpreadsheetApp:{openById:()=>({})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||'',setProperty:(k,v)=>properties.set(k,v)})}};vm.createContext(c);vm.runInContext(code+'\n'+owners,c);return {c,properties};}
const fixture=()=>({schedule:{'2026-09-14':['AA','BB','DC','EE','FF']},vacations:[],highlights:{},contacts:{AA:'aa@example.invalid',BB:'bb@example.invalid',CR:'cr@example.invalid',LH:'lh@example.invalid',EE:'ee@example.invalid',FF:'ff@example.invalid'}});
test('first available position advances in ascending order for vacation and replacement events',()=>{const {c}=setup();const data=fixture();assert.equal(c.selectResponsible_('2026-09-14',data).sigla,'AA');data.vacations=[{start:'2026-09-14',end:'2026-09-15',label:'AA (férias)'}];assert.equal(c.selectResponsible_('2026-09-14',data).sigla,'BB');data.replacementEvents={'2026-09-14':{people:['BB','CR'],unresolved:false}};const selected=c.selectResponsible_('2026-09-14',data);assert.equal(selected.sigla,'LH');assert.equal(selected.position,3);});
test('event highlights alone do not remove the first position',()=>{const {c}=setup();const data=fixture();data.highlights={'2026-09-14':['EVENTO: AA']};assert.equal(c.selectResponsible_('2026-09-14',data).sigla,'AA');});
test('only actual replacement records exclude members; delays and support do not',()=>{const {c}=setup();const events=c.replacementEvents_([['','14/09/2026','Pessoa A','CONGRESSO','','','Pessoa B'],['','14/09/2026','BB','ATRASO','','',''],['','14/09/2026','EE','PESSOAL','','',''],['','14/09/2026','SUPORTE','SUPORTE','','','Pessoa C']],{'PESSOA A':'AA'},{});assert.deepEqual(Array.from(events['2026-09-14'].people),['AA']);assert.equal(events['2026-09-14'].unresolved,false);});
test('unmapped absent member blocks an unverified assignment',()=>{const {c}=setup();const data=fixture();data.replacementEvents=c.replacementEvents_([['','14/09/2026','Nome desconhecido','CONGRESSO','','','Substituto']],{},{});assert.equal(c.selectResponsible_('2026-09-14',data).email,null);});
test('missing schedule sources do not invent a responsible person',()=>{const {c}=setup();assert.equal(c.selectResponsible_('2026-09-14',{error:'indisponível'}).email,null);const data=fixture();data.schedule['2026-09-14']=[];assert.equal(c.selectResponsible_('2026-09-14',data).email,null);});
test('daily reads skip score writes only after scheduled scoring is enabled',()=>{for(const enabled of [false,true]){const {c}=setup(enabled);let writes=0;c.authenticate_=()=>({email:'test@example.invalid'});c.report_=()=>({ok:true,day:'2026-09-14',items:[],signature:null});c.syncChecklistScore_=()=>writes++;c.responsibleForDay_=()=>({email:null});const value=JSON.parse(c.doPost({postData:{contents:'{"action":"report","day":"2026-09-14"}'}}).text);assert.equal(value.ok,true);assert.equal(writes,enabled?0:1);}});
test('trigger activation flag is written only after successful trigger creation',()=>{const {c,properties}=setup();const chain={timeBased(){return this;},everyDays(){return this;},atHour(){return this;},inTimezone(tz){assert.equal(tz,'America/Sao_Paulo');return this;},create(){throw new Error('quota');}};c.ScriptApp={getProjectTriggers:()=>[],newTrigger:()=>chain};assert.throws(()=>c.installChecklistScoreTrigger(),/quota/);assert.equal(properties.get('CHECKLIST_SCHEDULED_SCORE'),undefined);chain.create=()=>({});c.installChecklistScoreTrigger();assert.equal(properties.get('CHECKLIST_SCHEDULED_SCORE'),'1');});
test('monthly report keeps complete calendar and authorized signer rules',()=>{const {c}=setup();const rows={Unidades:[['one','Test unit','qr','','']],Registros:[],Assinaturas:[],Assinantes:[['signer@example.invalid','Signer','SIM']]};c.rows_=(_,name)=>rows[name];c.safeSources_=()=>({error:'test offline'});const month=c.monthly_({},'2026-02',{email:'signer@example.invalid'},'2026-02-15');assert.equal(month.days.length,28);assert.equal(month.days[15].status,'future');assert.equal(month.days[0].status,'pending');assert.equal(c.report_({},'2026-02-01',{email:'other@example.invalid'},{units:rows.Unidades,records:[],signatures:[],signers:rows.Assinantes},'2026-02-15').canSign,false);});
test('signing still synchronizes points and denies accounts outside signers',()=>{for(const canSign of [true,false]){const {c}=setup(true);let scoreWrites=0,signatureWrites=0;c.authenticate_=()=>({email:'signer@example.invalid'});c.LockService={getScriptLock:()=>({waitLock(){},hasLock:()=>true,releaseLock(){}})};c.report_=()=>({ok:true,day:'2026-09-14',items:[{id:'one',record:{id:'record'}}],canSign,revision:'revision',signature:null});c.rows_=()=>[];c.append_=()=>signatureWrites++;c.ensureSignatureJustificationHeader_=()=>{};c.responsibleForDay_=()=>({email:'signer@example.invalid'});c.syncChecklistScore_=()=>scoreWrites++;c.SpreadsheetApp.flush=()=>{};const value=JSON.parse(c.doPost({postData:{contents:JSON.stringify({action:'sign',day:'2026-09-14',revision:'revision',accepted:true,requestId:'12345678-1234-1234'})}}).text);assert.equal(value.ok,canSign);assert.equal(signatureWrites,canSign?1:0);assert.equal(scoreWrites,canSign?1:0);}});
