// Compile existing screens into native modules. No eval, application iframes or runtime build dependencies.
import fs from 'node:fs/promises';
import path from 'node:path';
import postcss from 'postcss';
import selectorParser from 'postcss-selector-parser';
const specs = { home:'', eventos:'apps/eventos/', etiquetas:'apps/etiquetas/', gestao:'apps/gestao/', checklist:'apps/checklist/', treinamentos:'apps/treinamentos/' };
const attr = (tag,name) => tag.match(new RegExp('\\b'+name+'=["\\\']([^"\\\']*)["\\\']','i'))?.[1];
const resolve = (base,p) => path.posix.normalize(path.posix.join(base,p.split('?')[0]));
function cssScope(css,base) {
  const sheet=postcss.parse(css);
  sheet.walkRules(rule=>{
    if(rule.parent?.type==='atrule' && /keyframes$/i.test(rule.parent.name))return;
    rule.selector=selectorParser(selectors=>selectors.walk(node=>{
      if(node.type==='pseudo'&&node.value===':root')node.value=':host';
      if(node.type==='tag'&&node.value==='html')node.replaceWith(selectorParser.pseudo({value:':host'}));
      if(node.type==='tag'&&node.value==='body')node.replaceWith(selectorParser.attribute({attribute:'data-module-body'}));
    })).processSync(rule.selector);
  });
  sheet.walkDecls(decl=>{decl.value=decl.value.replace(/url\(\s*(["']?)([^)'"\s]+)\1\s*\)/g,(all,q,url)=>/^(data:|https?:|#)/.test(url)?all:`url("__SAHMT_BASE__${resolve(base,url)}")`);});
  return sheet.toString();
}
for(const [id,base] of Object.entries(specs)) {
  const html=await fs.readFile(`ui/templates/${id}.html`,'utf8');
  let body=html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)[1].replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
  // Former application frames are obsolete; their containers remain for compatibility with existing selectors.
  body=body.replace(/<iframe\b[^>]*>[\s\S]*?<\/iframe>/gi,'');
  const styles=[],vendors=[],chunks=[];
  for(const tag of html.matchAll(/<link\b[^>]*>/gi)) {
    if(attr(tag[0],'rel')!=='stylesheet')continue;
    const href=attr(tag[0],'href');
    if(/^https?:/.test(href)) continue; // system font fallback; avoids a blocking external font request
    const p=resolve(base,href); styles.push(cssScope(await fs.readFile(p,'utf8'),path.posix.dirname(p)+'/'));
  }
  for(const m of html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi))styles.push(cssScope(m[1],base));
  for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const src=attr(m[1],'src');
    if(src && /auth\/shared-auth|integration\/sahmt-checklist/.test(src))continue;
    if(src && (/^https?:/.test(src)||src.includes('vendor/'))){vendors.push(/^https?:/.test(src)?src:resolve(base,src));continue;}
    let js=src?await fs.readFile(resolve(base,src),'utf8'):m[2];
    js=js.replace(/^\uFEFF/,'');
    // The root shell alone owns installation, history and service-worker lifecycle.
    js=js.replace(/if\s*\(\s*["']serviceWorker["']\s+in\s+navigator\s*\)/g,'if (false)');
    chunks.push(`{\n${js}\n}`);
  }
  await fs.writeFile(`core/views/${id}.json`,JSON.stringify({id,base,title:html.match(/<title>(.*?)<\/title>/s)?.[1]||'SAHMT',html:body,css:styles.join('\n'),vendors}));
  await fs.writeFile(`core/views/${id}.js`,`// Generated by scripts/build.mjs — edit original module sources, then rebuild.\nexport async function mount(ctx) {\nconst {document,window,navigator,location,history,fetch,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame,cancelAnimationFrame}=ctx;\n${id==='checklist'?"window.SAHMT_CHECKLIST_CONTRACT = (await import('../checklist-contract.js')).checklistResponse;":''}\n${chunks.join('\n')}\n}\n`);
}
console.log('Built six native modules.');
